#!/bin/sh
BASE="$(basename "$ARGV0")"
cd "$APPDIR/usr"

if [ -f "bin/$BASE" ]; then
    exec "bin/$BASE" "$@"
fi

if [ $# -ge 1 ]; then
    APP="bin/$1"
    if [ -f "$APP" ]; then
	shift
	exec "$APP" "$@"
    fi

    echo "Usage: $ARGV0 [command [arguments...]]" 1>&2
    echo "Run without command to setup." 1>&2
    echo 1>&2
    echo "Available commands:" 1>&2
    ls -1 bin 1>&2
    exit 1
fi

if ! which ibus > /dev/null ; then
    bin/notify-send -u critical "ibus-rime setup" "ibus not found!"
    echo "ibus not found!"
    exit 1
fi

setup() {
    IBUS_PREFIX="$(dirname $(which ibus))/.."
    USER_DIR="$HOME/.config/ibus/rime"
    LOCAL_DIR="$USER_DIR/appimage"

    mkdir -p "$LOCAL_DIR" &&
    cp "$APPDIR/ibus-rime.png" "$LOCAL_DIR" &&
    sed -e "s#%ICON%#$LOCAL_DIR/ibus-rime.png#g" \
        -e "s#%ENGINE%#$APPIMAGE#g" \
        "$APPDIR/rime.xml.in" > "$LOCAL_DIR/rime.xml" &&

    IBUS_COMPONENT_PATH="$LOCAL_DIR":"$IBUS_PREFIX/share/ibus/component" ibus write-cache &&

    bin/rime_deployer --build "$USER_DIR" share/rime-data
}

bin/notify-send "ibus-rime setup" "Deploying..."
if ! setup ; then
    bin/notify-send -u critical "ibus-rime setup" "Fail!"
else
    bin/notify-send "ibus-rime setup" "Done! Please restart ibus."
fi
