#!/bin/sh
BASE="$(basename "$ARGV0")"
BINDIR="$APPDIR/usr/bin"

if [ -f "$BINDIR/$BASE" ]; then
    exec "$APPDIR/usr/lib/exec0" "$BINDIR/$BASE" "$@"
fi

if [ $# -ge 1 ]; then
    APP="$BINDIR/$1"
    if [ -f "$APP" ]; then
        ARGV0="$ARGV0 $1"
        shift
        exec "$APPDIR/usr/lib/exec0" "$APP" "$@"
    fi

    echo "Usage: $ARGV0 [command [arguments...]]" 1>&2
    echo 1>&2
    echo "Run without command to setup." 1>&2
    echo 1>&2
    echo "Available commands:" 1>&2
    ls -1 "$BINDIR" 1>&2
    exit 1
fi

if ! which ibus > /dev/null ; then
    "$BINDIR/notify-send" -u critical "ibus-rime setup" "ibus not found!"
    echo "ibus not found!"
    exit 1
fi

quote_string () {
    echo "$1" |
	sed "s/'/\'\\\'\'/g" | sed "s/^\(.*\)$/'\1'/g" |  # shell quote
	sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' | # xml quote
	sed 's/\\/\\\\/g' | sed 's/&/\\\&/g' | sed 's/#/\\#/g' # sed quote
}

setup() {
    IBUS_PREFIX="$(dirname $(which ibus))/.."
    USER_DIR="$HOME/.config/ibus/rime"
    LOCAL_DIR="$USER_DIR/appimage"
    QUOTED_ENGINE_PATH=$(quote_string "$APPIMAGE")
    QUOTED_ICON_PATH=$(quote_string "$LOCAL_DIR/ibus-rime.png")

    mkdir -p "$LOCAL_DIR" &&
    cp "$APPDIR/ibus-rime.png" "$LOCAL_DIR" &&
    sed -e "s#%ICON%#$QUOTED_ICON_PATH#g" \
        -e "s#%ENGINE%#$QUOTED_ENGINE_PATH#g" \
        "$APPDIR/rime.xml.in" > "$LOCAL_DIR/rime.xml" &&

    if ibus read-cache --system ; then
        pkexec env IBUS_COMPONENT_PATH="$LOCAL_DIR":"$IBUS_PREFIX/share/ibus/component" ibus write-cache --system
    else
        IBUS_COMPONENT_PATH="$LOCAL_DIR":"$IBUS_PREFIX/share/ibus/component" ibus write-cache
    fi &&

    "$BINDIR/rime_deployer" --build "$USER_DIR" "$APPDIR/usr/share/rime-data"
}

"$BINDIR/notify-send" "ibus-rime setup" "Deploying..."
if ! setup ; then
    "$BINDIR/notify-send" -u critical "ibus-rime setup" "Fail!"
else
    "$BINDIR/notify-send" "ibus-rime setup" "Done! Please restart ibus."
fi
