language: cpp
os: linux
compiler: gcc
dist: xenial

install:
#- sudo apt-get update -qq
- sudo apt-get install -qq build-essential libboost-dev libibus-1.0-dev libnotify-dev libnotify-bin --no-install-recommends

script:
- "./build.sh"

after_success:
 - bash upload.sh ibus-rime-x86_64.AppImage

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
