#!/bin/sh
PROJNAME=$(dirname "$1")
VERSION=$(git --git-dir="$1" describe --tags --always --exclude 'latest')
URL=$(git --git-dir="$1" config --get remote.origin.url)
echo "$PROJNAME" "$VERSION" "$URL"
