name: build

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: apt get
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq libfuse2

    - name: build docker image
      run: docker build -t build .

    - name: fetch
      run: ./build.sh fetch

    - name: build in docker image
      run: docker run -v $PWD:/work --rm build bash -c "cd /work; ./build.sh build"

    - name: bundle
      run: |
        sudo chown -R $USER AppDir
        ./build.sh bundle

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ibus-rime*.AppImage

    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash upload.sh ibus-rime*.AppImage
